name: Deploy Ephemeral Environment

on:
  push:
    branches:
      - 'test/**' 
  workflow_dispatch:

   
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 

      - name: Configure AWS Credentials # <-- MODIFICADO AQUI!
        uses: aws-actions/configure-aws-credentials@v4
        with:
          # ATENÇÃO: Usando AWS Access Key ID e Secret Access Key.
          # Armazene-as como GitHub Secrets.
          aws-access-key-id: ASIA4EAXXO7YIXKZ725K # <-- REFERÊNCIA AO SEGREDO
          aws-secret-access-key: l3QtYwexkl+Ck0FkhXlXtnyUbJXo3bVggOuXckps # <-- REFERÊNCIA AO SEGREDO
          aws-region: us-west-2

      - name: Load .env file
        uses: aarcangeli/load-dotenv@v1.0.0

      - name: Create Terraform configuration
        run: |
           aws rds create-db-instance \
            --db-instance-identifier testetestetstete \
            --db-instance-class db.t3.micro" \
            --db-snapshot-identifier arn:aws:rds:us-west-2:833273427952:snapshot:database-1-snapshot \

        env:
          DB_INSTANCE: ${{env.DB_INSTANCE}} 
